### ISSUE TITLE
[Feature Request] tensorclass with non-tensor data

### ISSUE THREAD

**Issue by vmoens** [pytorch-labs/tensordict#145]
## Motivation

`@tensorclass` is currently restricted to input types: `Tensor`, `MemmapTensor`, `KeyedJaggedTensor`, `TensorDictBase` or other `tensorclass`
Some users have expressed interest for a more generic type of content.

## Solution

We could store any other data but restrict the tensor-behaviours to the tensor data.

### returning a new instance
Any operation that return a tensorclass would just copy the non-tensor data:
```python
>>> @tensorclass
... class MyClass:
...     images: torch.Tensor
...     path: str
... 
>>> data = MyClass(torch.randn(2, 3, 64, 64), "path_to_data", batch_size=[2])
>>> print(data[0])
MyData(images=torch.Tensor(...), path="path_to_data", batch_size=[])
```

The same would do for `.contiguous()`, `.clone()`, `.unbind()`, etc
For `stack` or `cat` we would need to check that these attributes match. If not, an error is thrown.

### Indexing

In general, I think every non-tensor field should be treated in the same way, ie a list would not be indexed

```python
>>> @tensorclass
... class MyClass:
...     images: torch.Tensor
...     captions: List[str]
... 
>>> data = MyClass(torch.randn(2, 3, 64, 64), [“a”, “b”], batch_size=[2])
>>> print(data[0])
MyData(images=torch.Tensor(...), captions=["a", "b"], batch_size=[])
```

If the number of captions is limited this could work
```python
@tensorclass
class MyClass:
    images: torch.Tensor
    _captions: torch.Tensor
    caption_classes: List[str]

    @property 
    def captions(self):
        return [self.caption_classes[idx] for idx in self._captions]

data = MyClass(images=torch.randn(5, 3, 64, 64), _captions=torch.randint(2, (5,)), caption_classes=["a", "b"], batch_size=[5])

```

Otherwise, if the number of captions is much larger, it would be up to the user to implement indexing
```python
@tensorclass
class MyClass:
    images: torch.Tensor
    captions: List[str]

    def __getitem__(self, item):
        c = super().__getitem__(item)
        c.captions = self.captions[item]
        return c
```

### setitem

With tensorclass, we can do
```python
>>> @tensorclass
... class MyClass:
...     images: torch.Tensor
>>> data = MyClass(torch.randn(3, 4, 5), batch_size=[3, 4])
>>> data[1] = MyClass(torch.randn(4, 5), batch_size=[4])
```

With a non-tensor field, I would think about solving it that way
```python
>>> @tensorclass
... class MyClass:
...     images: torch.Tensor
...     meta_data: Optional[str] = None
>>> data = MyClass(torch.randn(3, 4, 5), "stuff", batch_size=[3, 4])
>>> data[1] = MyClass(torch.randn(4, 5), "stuff", batch_size=[4])  # match - no error
>>> data[1] = MyClass(torch.randn(4, 5), batch_size=[4])  # ignored - no error
>>> data[1] = MyClass(torch.randn(4, 5), "I am a pig, and as a pig, I have always stood out.", batch_size=[4])  # don't match - raise exception
>>> MyClass(torch.randn(3, 4, 5), batch_size=[3, 4])
>>> data[1] = MyClass(torch.randn(4, 5), "I am a pig, and as a pig, I have always stood out.", batch_size=[4])  # don't match - raise exception
```

### Construction

One important question is also whether we want to allow any field to be a non-tensor, e.g.
```python
>>> @tensorclass
... class MyClass:
...     images: torch.Tensor  # do we want to raise an exception if a string is given?
...     meta_data: Any  # will tensors be considered as tensors?
...     meta_data: Optional[str] = None  # do we want to raise an exception if a tensor is given?
```

cc @tcbegley @keyboardAnt

**Comment by shagunsodhani** [comment]
This is great! I have a couple of comments:

> Any operation that return a tensorclass would just copy the non-tensor data:

Deep copy or shallow copy ?

> In general, I think every non-tensor field should be treated in the same way, ie a list would not be indexed

+1 

> Otherwise, if the number of captions is much larger, it would be up to the user to implement indexing

A consistent behavior would be more apt

> `data[1] = MyClass(torch.randn(4, 5), "I am a pig, and as a pig, I have always stood out.", batch_size=[4])  # don't match - raise exception`

I didn't follow why doesnt it match ?

> meta_data: Any  # will tensors be considered as tensors?

In this case, are we relying to static types? If not, the user should be allowed to annotate `meta_data` as `Any` and assign it a tensor (as will be allowed by Python).

> meta_data: Optional[str] = None  # do we want to raise an exception if a tensor is given?

Depends on how much do we want to rely on static analysis. I am open to raising an exception but this may not be the behavior that the end users expect.

**Comment by vmoens** [comment]
> I didn't follow why doesn't it match ?

the string is different, hence we don't know what to do (unlike tensors, we don't know how to update the string of the destination class given a mismatching script from the origin)

> In this case, are we relying to static types? If not, the user should be allowed to annotate meta_data as Any and assign it a tensor (as will be allowed by Python).

My view is this: we should not care too much about type annotations. If the annotated type is the class itself, then yes we should care (we already do that). See this example, which should work with tensorclass as it is now:
```
@tensorclass
class MyClass:
    tensor: Any
    nested: Optional[MyClass] = None

data = MyClass(torch.randn(3, 4), MyClass(torch.zerso(3, 4), batch_size=[3, 4]), batch_size=[3, 4])
assert isinstance(data.nested, MyClass)
```
This is not as trivial as it seems because, under the hood, `nested` is actually stored as a tensordict and converted on the fly to a `MyClass` when queried. We do that based on the type annotation (since the user has said she wanted a `MyClass` we give her that).

To me, in all other cases, we should just look at the data in the following way:

```
def __setattr__(self, name, stuff):
    if isinstance(stuff, (Tensor, KeyedJaggedTensor, TensorDictBase)) or is_tensorclass(stuff):
        # write the data in self._tensordict
   else:
        return super().__setattr__(name, stuff)
```

The reason I don't want to rely too much on type annotations is because 
1. we need to make opinionated choices: e.g. what to do with `Any`? Is is always a simple attribute? Or should we look at the type and decide (like in the example above)? Then what should we do with `Union[Tensor, str]`? write the tensor as an attribute?
2. we deviate from `dataclass` where the type is not enforced at all (it is just indicative IIRC)
3.  it makes the learning curve steeper for the users: one will need to read way more doc to understand what can and can't be done.

In general, my philosophy is to have the behaviour that is the most intuitive. It is not always possible though... I feel that both behaviours (strict type or loose) are at first sight intuitive, but the former quickly ends up in not so obvious decisions that will harm adoption.

Wdyt?

> this may not be the behavior that the end users expect

Exactly my point

**Comment by sreevasthav** [comment]
Hi @vmoens,

I will work on this

**Comment by shagunsodhani** [comment]
>> I didn't follow why doesn't it match ?
> the string is different, hence we don't know what to do (unlike tensors, we don't know how to update the string of the destination class given a mismatching script from the origin)

My bad. I didnt realize we were indexing the class. Well then, the following seems weird:

> data = MyClass(torch.randn(3, 4, 5), "stuff", batch_size=[3, 4])
> data[1] = MyClass(torch.randn(4, 5), "stuff", batch_size=[4])  # match - no error

I mean `data[1]` can be thought of as a subclass of `MyClass` that only has `Tensor, MemmapTensor, KeyedJaggedTensor, TensorDictBase or other tensorclass` attributes.

>> In this case, are we relying to static types? If not, the user should be allowed to annotate meta_data as Any and assign it a tensor (as will be allowed by Python).

> My view is this: we should not care too much about type annotations. If the annotated type is the class itself, then yes we should care (we already do that).

> nested is actually stored as a tensordict and converted on the fly to a MyClass when queried. We do that based on the type annotation (since the user has said she wanted a MyClass we give her that).

> To me, in all other cases, we should just look at the data in the following way:

```
def __setattr__(self, name, stuff):
    if isinstance(stuff, (Tensor, KeyedJaggedTensor, TensorDictBase)) or is_tensorclass(stuff):
        # write the data in self._tensordict
   else:
        return super().__setattr__(name, stuff)
```

I am likely misunderstanding this but the two things seems different. In the first case (`since the user has said she wanted a MyClass we give her that`), we are relying on type hints but in the second case, we are directly testing the types. I agree with your later comment (and reasons) regarding `I don't want to rely too much on type annotations`.

**Comment by sreevasthav** [comment]
@vmoens ,
Couple of questions: 
1. Do we want to support any non-tensor data or we want to restrict this feature request to few data types like String or List? 
2. Regarding the indexing, the list can be the indices of the images. Do we not want to index the list if the len(list) and tensor matches?

**Comment by vmoens** [comment]
> Do we want to support any non-tensor data or we want to restrict this feature request to few data types like String or List?

Anything as far as I'm concerned

> Regarding the indexing, the list can be the indices of the images. Do we not want to index the list if the len(list) and tensor matches?

No, as stated before, `__getitem__` just calls `TensorDict.__getitem__`. If something else is wanted, one should code up her own `__getitem__` as presented [here](https://github.com/pytorch-labs/tensordict/issues/145#issue-1519081305). We want to be consistent across all non-tensor data.

**Comment by sreevasthav** [comment]
@vmoens 
How do we want to handle the nested usecase:
for example:
```
@tensorclass
class MyDataNested:
    X: torch.Tensor
    z: str
    y: MyDataNested = None
```
```
X = torch.ones(3, 4, 5)
z = 'test_tensorclass'
batch_size = [3, 4]
data_nest = MyDataNested(X=X, z=z, batch_size=batch_size)
data = MyDataNested(X=X, y=data_nest, z=z, batch_size=batch_size)
```
If I use nested, since we are internally converting the tensor_class to tensor_dict, we might lose the non-tensor data of the data_nest
Output:
```
MyDataNested(
    X=Tensor(torch.Size([3, 4, 5]), dtype=torch.float32),
    y=TensorDict(
        fields={
            X: Tensor(torch.Size([3, 4, 5]), dtype=torch.float32)},
        batch_size=torch.Size([3, 4]),
        device=None,
        is_shared=False),
    z='test_tensorclass',
    batch_size=torch.Size([3, 4]),
    device=None,
    is_shared=False)
```

**Comment by vmoens** [comment]
Good point
I think if you do `data.y` you should get a `MyDataNested` so we should do some magic to return `data.y.z` as being the `z` that you gave to the nested object

**Comment by sreevasthav** [comment]
@vmoens 
Couple of questions on nested usecase:
1. Do we support multiple nesting? This is what I mean:
```
@tensorclass
class MyDataNested:
    X: torch.Tensor
    y: MyDataNested = None

X = torch.ones(3, 4, 5)
batch_size = [3, 4]
data = MyDataNested(X=X,
                    y= MyDataNested(
                            X=MyDataNested(X=X, batch_size=batch_size),
                            batch_size=batch_size)
                    , batch_size=batch_size)
```
                    
While instantiating the object I did not get any error message. However, this is what I see when I try to access the attributes:

```
print(data)
MyDataNested(
    X=Tensor(torch.Size([3, 4, 5]), dtype=torch.float32),
    y=TensorDict(
        fields={
            X: TensorDict(
                fields={
                    X: Tensor(torch.Size([3, 4, 5]), dtype=torch.float32)},
                batch_size=torch.Size([3, 4]),
                device=None,
                is_shared=False)},
        batch_size=torch.Size([3, 4]),
        device=None,
        is_shared=False),
    batch_size=torch.Size([3, 4]),
    device=None,
    is_shared=False)
```
    
```
print(data.y)
MyDataNested(
    X=TensorDict(
        fields={
            X: Tensor(torch.Size([3, 4, 5]), dtype=torch.float32)},
        batch_size=torch.Size([3, 4]),
        device=None,
        is_shared=False),
    batch_size=torch.Size([3, 4]),
    device=None,
    is_shared=False)
```
    
```
print(data.y.X)
TensorDict(
    fields={
        X: Tensor(torch.Size([3, 4, 5]), dtype=torch.float32)},
    batch_size=torch.Size([3, 4]),
    device=None,
    is_shared=False)
```
    
Here data.y.X is supposed to be return as MyDataNested class instead returned a TensorDict. 
   
   2. Regarding the support for non-tensor data, the changes I made in the PR so far passes all the test cases except nested scenario. I was thinking of saving non-tensor data at a global class level attribute and retrieve it while accessing the attribute. This choice has a limitation if the non-tensor data is optional and we don't know what internal objects set this attribute? Any suggestion on how to proceed with this?
