### ISSUE TITLE
[BUG] Unexpected shape change during pre-allocation

### ISSUE THREAD

**Issue by btx0424** [pytorch-labs/tensordict#190]
## Describe the bug

The use case is to implement a lazily initialized rollout buffer for RL. However, when setting a nested `TensorDict` with finer-grained `batch_size` at index 0, the allocated buffer tensors get truncated `batch_size` while also changing the shape of the original `TensorDict`.

## To Reproduce

```python
import torch
from tensordict import TensorDict

buffer = TensorDict({}, batch_size=[500, 1024])

td_0 = TensorDict({
    "env.time": torch.rand(1024, 1),
    "agent.obs": TensorDict({ # assuming 3 agents in a multi-agent setting
        "image": torch.rand(1024, 3, 64),
        "state": torch.rand(1024, 3, 3, 32, 32)
    }, batch_size=[1024, 3])
}, batch_size=[1024])

td_1 = td_0.clone()
buffer[0] = td_0
buffer[1] = td_1
```

This would trigger

```
RuntimeError: indexed destination TensorDict batch size is torch.Size([1024]) (batch_size = torch.Size([500, 1024]), index=1), which differs from the source batch size torch.Size([1024, 3])
```

at `buffer[1] = td_1`. And the batch sizes of both `buffer["b"]` and `td_0["b"]` become `[1024]`.

## Expected behavior

The batch sizes of both `buffer["b"]` and `td_0["b"]` being `[1024, 3]`, and `buffer[1] = td_1` being successful.

## System info

tensordict: 0.0.1c

## Reason and Possible fixes

The cause looks to be around https://github.com/pytorch-labs/tensordict/blob/main/tensordict/tensordict.py#L1973 and https://github.com/pytorch-labs/tensordict/blob/main/tensordict/tensordict.py#L3393 where the target shape is unexpectedly considered to be incongruent:

```python
# L1973, TensorDictBase.__setitem__
def __setitem__(
    self, index: INDEX_TYPING, value: Union[TensorDictBase, dict]
) -> None:
    ...
    if value.batch_size != indexed_bs:
        raise RuntimeError(
            f"indexed destination TensorDict batch size is {indexed_bs} "
            f"(batch_size = {self.batch_size}, index={index}), "
            f"which differs from the source batch size {value.batch_size}"
        )
    ...

#L3393, SubTensorDict.set
...
def set(
    self,
    key: NESTED_KEY,
    tensor: Union[dict, COMPATIBLE_TYPES],
    inplace: bool = False,
    _run_checks: bool = True,
) -> TensorDictBase:
    ...
    if isinstance(tensor, TensorDictBase) and tensor.batch_size != self.batch_size:
        tensor.batch_size = self.batch_size
    ...
```

A possible fix would be changing to `if value.batch_size[: len(indexed_bs)] != indexed_bs` and `if isinstance(tensor, TensorDictBase) and tensor.batch_size[: len(self.batch_size)] != self.batch_size`, respectively. All existing tests still pass after the modification.

It's really a minor problem and later I found `torchrl.data.TensorDictReplayBuffer` with `LazyTensorStorage` to be a working alternative. But it's also interesting to see they are implemented differently.

I'm glad to fix it if you would like.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
If you want to fix it, it would be wonderful 

Just also add a tests today check non regression
