### ISSUE TITLE
[BUG] Conflicting keys silently collide in `tensordict.unflatten_keys`

### ISSUE THREAD

**Issue by vmoens** [pytorch-labs/tensordict#29]
## Describe the bug

If two keys have the same resulting index in `flatten_keys` and `unflatten_keys`, they will be overwritten without an error being raised. This may lead to unexpected behaviours down the line.

## To Reproduce

We would expect this code to fail:
```python
from tensordict import TensorDict
import torch
t = TensorDict({'a.a': torch.randn(3), 'a': {'a': torch.randn(3)}}, [])
print(t.unflatten_keys('.'))
```
as `("a", "a")` already exists.
Similarly, 
```
from tensordict import TensorDict
import torch
t = TensorDict({'a.a': torch.randn(3), 'a': {'a': torch.randn(3)}}, [])
print(t.flatten_keys('.'))
```
should also fail as `"a.a"` is also an existing key.

**Comment by khundman** [comment]
working on this
