### ISSUE TITLE
[BUG] Global "indexing" of tensorclasses types leads to type conflicts

### ISSUE THREAD

**Issue by apbard** [pytorch-labs/tensordict#297]
debugging test failures from #293 we found out that the solution based on [CLASSES_DICT](https://github.com/pytorch-labs/tensordict/blob/8ab67e42dadd84770452987399efe4f481d9337e/tensordict/prototype/tensorclass.py#L40)
leads to weird behaviour when classes with the same name are being defined (even if locally)

getting the type directly from the instatiated object instead of using the annotation might solve the problem

**Comment by vmoens** [comment]
Can you provide a minimally reproducible example for me to work on?

**Comment by apbard** [comment]
I am already working on this
