### ISSUE TITLE
Default batch_size + TensorDictModule can be surprising

### ISSUE THREAD

**Issue by apbard** [pytorch-labs/tensordict#313]
TensordictModule allows to use a tensordict/class as input to the forward module. But it also support the nn.Module style call with tensors.
Under the hood it creates a new [tensordict](https://github.com/pytorch-labs/tensordict/blob/main/tensordict/nn/common.py#L253) that then forwards to the call method. In doing so, however, it uses the [default batch_size](https://github.com/pytorch-labs/tensordict/blob/e92f26366472a47aff93a0838716af4f5349191f/tensordict/tensordict.py#L3012).

I would say that using the maximum size is probably not the most common case. Can we reconsider the default or find a way to get the right size from the model itself?

**Comment by vmoens** [comment]
I guess your point is that then writing onto that tensordict can be problematic if the output shape violates it, right?
Sure I think we can remove that
