### ISSUE TITLE
[Feature Request] allow infering the batch size from a dict when creating a tensordict instance

### ISSUE THREAD

**Issue by taochenshh** [pytorch-labs/tensordict#328]
## Motivation

Suppose I have a dictionary as follows:
```
x = {'a':torch.randn(4,3), 'b': torch.randn(4,5)}
```
If I want to convert this to a tensordict, I will get an error if I don't specify the batch size:
```
y = TensorDict(x)  # won't run
```
In this case, can we support inferring the batch size from the first common dimension?

This is quite useful when integrating tensordict with other libraries. For example, in HuggingFace Accelerate, it converts the network output to the right precision by using [ConvertOutputsToFp32](https://github.com/huggingface/accelerate/blob/main/src/accelerate/utils/operations.py#L508). But it won't work with Tensordict currently because Tensordict does not allow creating a tensordict instance without explicitly specifying the batch size. The specific line that errors out is [this](https://github.com/huggingface/accelerate/blob/main/src/accelerate/utils/operations.py#L107).

**Comment by vmoens** [comment]
There is a `TensorDict.from_dict` method though, would that solve your issue?
Inferring the batch size automatically introduces a substential overhead and often breaks when you populate a TensorDict one item at a time

**Comment by taochenshh** [comment]
i see, thanks!
