### ISSUE TITLE
[Feature Request] TensorDict to support data classes

### ISSUE THREAD

**Issue by vyeevani** [pytorch-labs/tensordict#341]
## Motivation
Keeping track of what keys go into the tensordict can be challenging across a large codebase. Especially given the tensordicts interior key mutability where different modules could return tensordicts with different key naming conventions.

## Solution
1. Statically typed tensordict for a dataclass where every member of the data class must either be a tensordict or a PyTorch tensor. 
2. Being able to create tensordicts with lists of named tuples/dataclasses.
3. Being able to index into the tensordict and get back the data class you created the tensordict with.

## Alternatives

I haven't thought too much about alternatives.

## Additional context

This is heavily inspired by Jax's data class style approach for functional programming. It seems to me that at a high level, tensordicts are trying to achieve a similar thing to Jax's usage of pytrees except specifically with tensors.

## Checklist

- [ x] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
Have you had the chance to check @tensorclass? 
Here's a tutorial: https://pytorch-labs.github.io/tensordict/tutorials/tensorclass_fashion.html
you can put tensordicts in tensorclasses and do the opposite too. 
Is there any missing feature?

**Comment by vyeevani** [comment]
Nope this looks very comprehensive. My bad for missing this
