### ISSUE TITLE
[BUG] Performance drops after long time

### ISSUE THREAD

**Issue by patchmeifyoucan** [pytorch-labs/tensordict#401]
Hello,

thank you for creating TensorDict, it helps me a lot.

I use TensorDict as rolling replay buffer in a Reinforcement Learning application. I need lots of storage since my data involves images. The memmap feature is very handy in this case. Recently, I started seeing sharp performance drops during training after running for quite some time. This usually indicates that there are some tensors leaking and are not being collected. 

After days I was able to track this issue down to my replay buffer implementation, which you can find below. The problem occurs when running many iterations over time. The performance drop seems to be caused more by `buffer.get()` rather than `buffer.put()`, even though `buffer.put()` also causes rather small performance drops over time. This happens for both small and large dicts.

There does not seem to be any issue when writing static data once (on iteration 0) and reading afterwards. Results seem to be cached and reading is super fast with no drop (at least I do not observe any).

```python
import os
import shutil
import sys
import uuid

import numpy as np
import psutil
import torch
from tensordict import TensorDict, MemmapTensor
from tqdm import tqdm


class TensorDictReplayBuffer:
    def __init__(self, max_size, prefix):
        super().__init__()
        self.max_size = max_size
        self.current_index = 0
        self.current_size = 0
        self.prefix = prefix

        self.cache = None
        self.separator = "."

    @property
    def size(self):
        return self.current_size

    def setup_cache(self, data: TensorDict):
        os.makedirs(self.prefix, exist_ok=True)
        template = {
            k: MemmapTensor(
                self.max_size, *v.shape,
                dtype=v.dtype, filename=os.path.join(self.prefix, k)
            )
            for k, v in data[0].to_tensordict().items()
        }
        self.cache = TensorDict(template, batch_size=[self.max_size])

    def put(self, data: TensorDict) -> None:
        data = data.flatten_keys(self.separator).clear_device_()
        if self.cache is None:
            self.setup_cache(data)

        n = len(data)
        indices = torch.arange(self.current_index, self.current_index + n) % self.max_size
        self.cache[indices] = data
        self.current_size = min(self.max_size, self.current_size + n)

    def get(self, batch_size: int) -> TensorDict:
        indices = np.random.choice(self.current_size, batch_size, replace=False)
        return self.cache[indices].unflatten_keys(self.separator)


def data():
    n = 10
    return TensorDict(
        dict(
            dummy=torch.ones(n, n)
        ),
        batch_size=[]
    )

shutil.rmtree("data", ignore_errors=True)
os.makedirs("data", exist_ok=True)
buffer = TensorDictReplayBuffer(max_size=1_000_000, prefix=f"data/{uuid.uuid4()}")
n_reads = 10000
n_per_iteration = 5
batch_size = 128

for i in range(1000):
    with tqdm(total=n_reads, file=sys.stdout, desc=f"Iteration {i}") as pbar:
        for _ in range(n_reads // n_per_iteration):

            trajectory = torch.stack([data() for _ in range(n_per_iteration)])

            # if i == 0:
            buffer.put(trajectory)

            for _ in range(n_per_iteration):
                if buffer.size >= batch_size:
                    batch = buffer.get(batch_size=batch_size)

                pbar.update(1)

        pbar.set_postfix(dict(
            gpu_mem_mb=torch.cuda.memory_allocated() / 1e6,
            cpu_mem_mb=psutil.Process().memory_info().rss / 1e6
        ))
```

Is this something that can be explained given my implementation? Is this even an intended use-case for mem-mapped dicts? Or is there any other way to accomplish this? 

Any pointers are appreciated. Thanks a lot.

**Comment by vmoens** [comment]
Thanks for reporting this, we'll try to figure it out, and sorry that you had to debug that for so long!

After running a couple of iterations on my MacBook I don't see any slowdown, after how long does that occur?
You log the cpu and gpu mem: how much do they increase? My CPU mem is steady (933 mb).

Here is my log
```
Iteration 0: 100%|██████████| 10000/10000 [00:47<00:00, 211.24it/s, gpu_mem_mb=0, cpu_mem_mb=879]
Iteration 1: 100%|██████████| 10000/10000 [00:42<00:00, 237.58it/s, gpu_mem_mb=0, cpu_mem_mb=888]
Iteration 2: 100%|██████████| 10000/10000 [00:46<00:00, 217.22it/s, gpu_mem_mb=0, cpu_mem_mb=921]
Iteration 3: 100%|██████████| 10000/10000 [00:44<00:00, 224.01it/s, gpu_mem_mb=0, cpu_mem_mb=933]
Iteration 4: 100%|██████████| 10000/10000 [00:46<00:00, 216.22it/s, gpu_mem_mb=0, cpu_mem_mb=933]
Iteration 5: 100%|██████████| 10000/10000 [00:48<00:00, 207.62it/s, gpu_mem_mb=0, cpu_mem_mb=933]
```

**Comment by patchmeifyoucan** [comment]
Thanks for replying so quickly. I updated the code snippet to use smaller tensors, this way the iterations are faster and the effect becomes more evident. 

My code snippet is part of a bigger training loop, and only there I see an increase of memory. It may or may not be related actually. I tried to disentangle it as much as possible since during training the training code needs to run for ~1h for this effect to happen.


My output looks like this:

```
Iteration 0: 100%|██████████| 10000/10000 [00:01<00:00, 9792.55it/s, gpu_mem_mb=0, cpu_mem_mb=347]
Iteration 1: 100%|██████████| 10000/10000 [00:01<00:00, 5208.01it/s, gpu_mem_mb=0, cpu_mem_mb=347]
Iteration 2: 100%|██████████| 10000/10000 [00:02<00:00, 3500.33it/s, gpu_mem_mb=0, cpu_mem_mb=348]
Iteration 3: 100%|██████████| 10000/10000 [00:03<00:00, 2729.74it/s, gpu_mem_mb=0, cpu_mem_mb=348]
Iteration 4: 100%|██████████| 10000/10000 [00:04<00:00, 2089.78it/s, gpu_mem_mb=0, cpu_mem_mb=348]
```

In case this is a weird, OS-dependent issue, here's my full dependnecy config:
[dependencies.zip](https://github.com/pytorch-labs/tensordict/files/11602132/dependencies.zip)

I am using the latest [Poetry](https://python-poetry.org/docs/) version due to some [issues with PyTorch](https://github.com/python-poetry/poetry/issues/6409).
```bash
curl -sSL https://install.python-poetry.org | python3 - --version 1.5.1
```

**Comment by patchmeifyoucan** [comment]
Any updates here? If you have trouble reproducing it I could try to set up a Docker container such that you can see the effect.
