### ISSUE TITLE
[Feature Request] Caching keys

### ISSUE THREAD

**Issue by vmoens** [pytorch-labs/tensordict#43]
## Motivation

Getting the list of keys can be expensive, especially when we ask for the nested keys.
We could perhaps cache them.

Updating the tensordict (either using `set`, `update`, `setdefault`, `rename`, `select`, `exclude`) would trigger an update of the keys.

The major blocker for this is that modifying a nested tensordict should impact the parent tensordict, which implementation may open the door to a pandora box that we may want to keep close (ie having a parenting mechanism similar to replay buffers or transforms):

```python
subtd = TensorDIct({"b": [3]}, [])
tensordict = TensorDict({"a": subtd}, [])
subtd["c"] = [1]  # tensordict should be informed about this too
```

cc @tcbegley

**Comment by shagunsodhani** [comment]
Do you plan to enable this optimization out of the box? Asking as this can slow down a bunch of other operations and may come out as a surprise to the users.

**Comment by vmoens** [comment]
If I was to implement it I would just make it so that once you query the keys they are cached for the future, hence there wouldn't be any overhead. 
But the case of changing nested tensordicts is going to be hard to account for... I don't plan on working on this soon.

From a runtime perspective there are many other things we can work on improving before attacking that one.

**Comment by shagunsodhani** [comment]
> hence there wouldn't be any overhead.

There is the overhead of updating the cache for write / update ops (ignoring the nested keys stuff). We may also have to consider if this breaks thread-safety. I think Python dicts are thread-safe.

**Comment by vmoens** [comment]
Ok seems like it's going to be a lot of trouble for not much reward :) 
Let's close this for now, happy to re-open if there's a case for it
