### ISSUE TITLE
[BUG] Function signature of `to` incompatible with torch Module

### ISSUE THREAD

**Issue by vonHartz** [pytorch-labs/tensordict#513]
## Describe the bug
The signature of the `to` function of the [TensorDict](https://github.com/pytorch-labs/tensordict/blob/879678435e52d2610e4bb820cb4878cd01caec7e/tensordict/tensordict.py#L4415) is incompatible with that of [torch.nn.module](https://github.com/pytorch/pytorch/blob/5ed60477a7cd930298dbdab71046ec62024427c4/torch/nn/modules/module.py#L1042)

## To Reproduce

When assigning a TensorDict to a Buffer as shown [here](https://github.com/pytorch-labs/tensordict/blob/879678435e52d2610e4bb820cb4878cd01caec7e/test/test_nn.py#L2572) and then calling `to` on the underlying Module, it raises `TypeError: TensorDict.to() takes 2 positional argument but 4 were given`, as it tries to apply `to` with its own expected function signature.

## Expected behavior

The TensorDict should have an identical function signature to be compatible with torch Modules.
The additional batch_size argument could be added as an additional kwarg without breaking anything.

## System info

Describe the characteristic of your environment:
 * Python 3.10
 * torch 1.13.2
 * tensordict-nighly from pip

## Reason and Possible fixes

As explained above, the functions signatures are different between torch.nn.Module and TensorDict.
TensorDict should follow torch's format and only add its own batchsize arg.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for flagging this
It is true that the signature differs and there is a case for it to match the tensor.to signature.
Initially, we thought that `to(dtype)` whould not make sense since the dtype is completely free within a tensordict. However, it is also the case for a nn.Module but you can still cast a module parameters to a desired dtype... 
I'm open to change this! It's on our todo list.

**Comment by vmoens** [comment]
https://github.com/pytorch-labs/tensordict/pull/520 is ready for review
I made the `to` work like `Tensor.to` since `TensorDict` is a tensor-like class (not a module-like class) but the difference shouldn't be too important IMO
